services:
  marketplace:
    image: str1kez/marketplace_tg:dev
    build: .
    command: sh -c "python3 manage.py makemigrations marketplace; python3 manage.py migrate; python3 manage.py collectstatic --noinput; python3 manage.py createsuperuser --noinput --username $DJANGO_USERNAME --email lol@lol.ru; python3 app.py"
    ports:
      # - 192.168.1.3:80:8001
      - 8001:8001
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432
